# Generated by Django 5.1.5 on 2025-01-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["name", "created_at", "is_created", "viewing"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.AlterField(
            model_name="blog",
            name="is_created",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="viewing",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
